import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'


import "./globals.css";
import Nav from "../components/Nav";
import { cookies } from "next/headers";
import { redirect } from 'next/navigation'


export const metadata = {
  title: "SP database",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  

  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Nav />
            <SignedIn>
             {children}
            </SignedIn>
            <SignedOut>
              <div className="flex flex-col items-center justify-center h-screen">
                <h1 className="text-4xl font-bold">Welcome to the SP database</h1>
                <SignInButton className="bg-blue-500 text-white py-2 px-4 rounded-md cursor-pointer hover:bg-blue-600" />
              </div>
            </SignedOut>
          </body>
      </html>
    </ClerkProvider>
  );
}