import {authorized, login} from "@/components/authorized";
import "./globals.css";
import Nav from "../components/Nav";
import { redirect } from 'next/navigation'
import Link from "next/link";
import Loginpage from "@/components/login_page";



export const metadata = {
  title: "SP database",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const handleSubmission = async (event) => {
  //   event.preventDefault();
  //   const formData = new FormData(event.target);
  //   login(formData);
  // };

  return (
    <html lang="en">
      <body>
        <Nav />
        {authorized() ? (
          children
        ) : (
          <div className="flex flex-col items-center justify-center h-screen">
            <h1 className="text-4xl font-bold">
              Du har ikke adgang til denne side
            </h1>
            <Loginpage />
          </div>
        )}
      </body>
    </html>
  );
}